[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run build && npm run preview"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"